unsafe is now required (--cfg no_fail_on_missing_unsafe to bypass) (#408)
`unsafe` is now required. We generate a helpful error that should guide users to replace `#[ctor]` with `#[ctor(unsafe)]`

```
error: Missing unsafe keyword in #[ctor] annotation. Use #[ctor(unsafe)]. This error can
be suppressed by passing `--cfg no_fail_on_missing_unsafe` in `RUSTFLAGS` or placing
this in your `config.toml` file.

       #[ctor]
       ^^^^^^^------- replace this with #[ctor(unsafe)]

 --> tests/errors/ctor_no_unsafe.rs:3:1
  |
3 | #[ctor]
```